// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

// GlobalLeaderboardDesc represents a row from '[custom global_leaderboard_desc]'.
type GlobalLeaderboardDesc struct {
	User  string // user
	Score int    // score
}

// GlobalLeaderboardDescsByOffset runs a custom query, returning results as GlobalLeaderboardDesc.
func GlobalLeaderboardDescsByOffset(db XODB, offset int) ([]*GlobalLeaderboardDesc, error) {
	var err error

	// sql query
	const sqlstr = `select "user", "score" ` +
		`from global_rankings ` +
		`order by score desc ` +
		`limit 10 offset $1`

	// run query
	XOLog(sqlstr, offset)
	q, err := db.Query(sqlstr, offset)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*GlobalLeaderboardDesc{}
	for q.Next() {
		gld := GlobalLeaderboardDesc{}

		// scan
		err = q.Scan(&gld.User, &gld.Score)
		if err != nil {
			return nil, err
		}

		res = append(res, &gld)
	}

	return res, nil
}
