// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

// GuildLeaderboardDesc represents a row from '[custom guild_leaderboard_desc]'.
type GuildLeaderboardDesc struct {
	User  string // user
	Score int    // score
}

// GuildLeaderboardDescsByGuildOffest runs a custom query, returning results as GuildLeaderboardDesc.
func GuildLeaderboardDescsByGuildOffest(db XODB, guild string, offest int) ([]*GuildLeaderboardDesc, error) {
	var err error

	// sql query
	const sqlstr = `select "user", "score" ` +
		`from guild_rankings ` +
		`where guild = $1 ` +
		`order by score desc ` +
		`limit 10 offset $2`

	// run query
	XOLog(sqlstr, guild, offest)
	q, err := db.Query(sqlstr, guild, offest)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*GuildLeaderboardDesc{}
	for q.Next() {
		gld := GuildLeaderboardDesc{}

		// scan
		err = q.Scan(&gld.User, &gld.Score)
		if err != nil {
			return nil, err
		}

		res = append(res, &gld)
	}

	return res, nil
}
