// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

// GuildLeaderboardCount represents a row from '[custom guild_leaderboard_count]'.
type GuildLeaderboardCount struct {
	Count int64 // count
}

// GetGuildLeaderboardCounts runs a custom query, returning results as GuildLeaderboardCount.
func GetGuildLeaderboardCounts(db XODB) ([]*GuildLeaderboardCount, error) {
	var err error

	// sql query
	const sqlstr = `select count("id") ` +
		`from guild_rankings`

	// run query
	XOLog(sqlstr)
	q, err := db.Query(sqlstr)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*GuildLeaderboardCount{}
	for q.Next() {
		glc := GuildLeaderboardCount{}

		// scan
		err = q.Scan(&glc.Count)
		if err != nil {
			return nil, err
		}

		res = append(res, &glc)
	}

	return res, nil
}
