// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"errors"
)

// LocationDensity represents a row from 'public.location_density'.
type LocationDensity struct {
	ID    string `json:"id"`    // id
	Lake  int    `json:"lake"`  // lake
	River int    `json:"river"` // river
	Ocean int    `json:"ocean"` // ocean

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the LocationDensity exists in the database.
func (ld *LocationDensity) Exists() bool {
	return ld._exists
}

// Deleted provides information if the LocationDensity has been deleted from the database.
func (ld *LocationDensity) Deleted() bool {
	return ld._deleted
}

// Insert inserts the LocationDensity to the database.
func (ld *LocationDensity) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if ld._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key must be provided
	const sqlstr = `INSERT INTO public.location_density (` +
		`id, lake, river, ocean` +
		`) VALUES (` +
		`$1, $2, $3, $4` +
		`)`

	// run query
	XOLog(sqlstr, ld.ID, ld.Lake, ld.River, ld.Ocean)
	err = db.QueryRow(sqlstr, ld.ID, ld.Lake, ld.River, ld.Ocean).Scan(&ld.ID)
	if err != nil {
		return err
	}

	// set existence
	ld._exists = true

	return nil
}

// Update updates the LocationDensity in the database.
func (ld *LocationDensity) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !ld._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if ld._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE public.location_density SET (` +
		`lake, river, ocean` +
		`) = ( ` +
		`$1, $2, $3` +
		`) WHERE id = $4`

	// run query
	XOLog(sqlstr, ld.Lake, ld.River, ld.Ocean, ld.ID)
	_, err = db.Exec(sqlstr, ld.Lake, ld.River, ld.Ocean, ld.ID)
	return err
}

// Save saves the LocationDensity to the database.
func (ld *LocationDensity) Save(db XODB) error {
	if ld.Exists() {
		return ld.Update(db)
	}

	return ld.Insert(db)
}

// Upsert performs an upsert for LocationDensity.
//
// NOTE: PostgreSQL 9.5+ only
func (ld *LocationDensity) Upsert(db XODB) error {
	var err error

	// if already exist, bail
	if ld._exists {
		return errors.New("insert failed: already exists")
	}

	// sql query
	const sqlstr = `INSERT INTO public.location_density (` +
		`id, lake, river, ocean` +
		`) VALUES (` +
		`$1, $2, $3, $4` +
		`) ON CONFLICT (id) DO UPDATE SET (` +
		`id, lake, river, ocean` +
		`) = (` +
		`EXCLUDED.id, EXCLUDED.lake, EXCLUDED.river, EXCLUDED.ocean` +
		`)`

	// run query
	XOLog(sqlstr, ld.ID, ld.Lake, ld.River, ld.Ocean)
	_, err = db.Exec(sqlstr, ld.ID, ld.Lake, ld.River, ld.Ocean)
	if err != nil {
		return err
	}

	// set existence
	ld._exists = true

	return nil
}

// Delete deletes the LocationDensity from the database.
func (ld *LocationDensity) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !ld._exists {
		return nil
	}

	// if deleted, bail
	if ld._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM public.location_density WHERE id = $1`

	// run query
	XOLog(sqlstr, ld.ID)
	_, err = db.Exec(sqlstr, ld.ID)
	if err != nil {
		return err
	}

	// set deleted
	ld._deleted = true

	return nil
}

// LocationDensityByID retrieves a row from 'public.location_density' as a LocationDensity.
//
// Generated from index 'location_density_pkey'.
func LocationDensityByID(db XODB, id string) (*LocationDensity, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, lake, river, ocean ` +
		`FROM public.location_density ` +
		`WHERE id = $1`

	// run query
	XOLog(sqlstr, id)
	ld := LocationDensity{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, id).Scan(&ld.ID, &ld.Lake, &ld.River, &ld.Ocean)
	if err != nil {
		return nil, err
	}

	return &ld, nil
}
